### ISSUE TITLE
Save credit card always displayed & not saved

### ISSUE THREAD

**Issue by julienanquetil** [wl-online-payments-direct/plugin-magento-creditcard#1]
There is two issues with the latest version (2.0.0)

- Even if we disable the "save token to account", it's still displayed on checkout (iframe mode)
- If we enable it, token is not saved to customer account (or db)

**Comment by mathieubroekaert** [comment]
Hello @julienanquetil 
Thank you for the feedback. We have improved this behavior in the version 2.1.1. Could you please update the plugin ? It should solve the issues you are facing.

**Comment by julienanquetil** [comment]
yes it's working now 👍
