### ISSUE TITLE
Preprod Tokenize

### ISSUE THREAD

**Issue by julienanquetil** [wl-online-payments-direct/plugin-magento-creditcard#11]
Hi,
Why this preprod URL is hardcoded and not the one according to settings (prod / test) ?

https://github.com/wl-online-payments-direct/plugin-magento-creditcard/blob/1d64521ab1f78dd30739f508609160b9a431b623/view/frontend/layout/checkout_index_index.xml#L4

Thanks

**Comment by WorldlineMagentoTeam** [comment]
Hello, Julien. For now, there is no difference between:
https://payment.direct.worldline-solutions.com/hostedtokenization/js/client/tokenizer.min.js
and
https://payment.preprod.direct.worldline-solutions.com/hostedtokenization/js/client/tokenizer.min.js
but it is a good point to make them switchable.

Thank you for your feedback!

**Comment by mathieubroekaert** [comment]
Hello Julien,
We don't (yet) use the one from the settings because in some cases you might want to change the Worldline domain, and the tokenizer.min.js file is not accessible through all Worldline domains - at the moment.
The moment it will be we will remove the hardcoding.
